export const LANDING = "/"
export const SIGN_UP = "/signup"
export const SIGN_IN = "/signin"
export const PASSWORD_FORGET = "/pw-forget"
export const HOME = "/home"
export const ACCOUNT = "/account"

export const Instructor = "/instructor"
export const Dashboard = "/dashboard"
export const Aquarium = "/aquarium"
export const Form = "/form"
export const Lab = "/lab"
export const Search = "/search"
export const Counter = "/counter"
export const Container = "/ada"
export const Tuto = "/tuto"
export const FORGET = "/forget"


export const Icons = "/icons"
export const Menu = "/menu"
export const Navigation_Horizontal = "/navigation"
export const Forms = "/forms"
export const Graphs = "/graphs"
export const BlockList = "/blockList"
export const colors = "/colors"
export const Media = "/media"
export const Elements = "/elements"
export const Avatars = "/avatars"
export const Topography = "/topography"

